### ISSUE TITLE
.start() requires a callback function to work

### ISSUE THREAD

**Issue by FunctionDJ** [LordVonAdel/os2l#1]
https://github.com/LordVonAdel/os2l/blob/4039db18325023c0d4d4f5c37ee2341bb0b08e99/OS2LServer.js#L113-L118

It checks if the callback parameter is speficified (not null) and will only then resolve the promise.
Moving the `resolve()` outside that block should resolve the issue, but i'm not sure so i'm not doing a PR.

Users can fix this issue by just passing a empty callback function to `.start()` for the time being:
`await server.start(() => {})`

**Comment by LordVonAdel** [comment]
Looks like an oversight. Thanks for the notice. I will fix it
