### ISSUE TITLE
UnhandledPromiseRejection when using autoReconnect without useDNS_SD

### ISSUE THREAD

**Issue by SeanBannister** [LordVonAdel/os2l#8]
Thanks so much for writing this code, I'm currently using VirtualDJ with Sunlite Suite and using this as a router to give me more advanced control.

If you run the client with `autoReconnect` set to  true and turn off `useDNS_SD` so that you're manually specifying the host and port, for example:

```
export let client = new OS2LClient({
  port: 8010,
  host: "127.0.0.1",
  useDNS_SD: false,
  autoReconnect: true
});
```

If the OS2L server isn't yet listening on the port, it'll throw an UnhandledPromiseRejection, because it can't connect on the retry.

> node:internal/process/promises:389
>       new UnhandledPromiseRejection(reason);
>       ^
> 
> UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".
>     at throwUnhandledRejectionsMode (node:internal/process/promises:389:7)
>     at processPromiseRejections (node:internal/process/promises:470:17)
>     at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
>   code: 'ERR_UNHANDLED_REJECTION'
>

**Comment by LordVonAdel** [comment]
Okay thanks for the info. I will look into it tomorrow.

**Comment by SeanBannister** [comment]
Thank you so much for fixing this, really appreciate it. I've just run some tests and so far seems to be working perfectly.
