### ISSUE TITLE
Warning: Error: Bad OS2L package received!

### ISSUE THREAD

**Issue by SeanBannister** [LordVonAdel/os2l#9]
On rare occasions I was getting "Warning: Error: Bad OS2L package received!" I did some debugging and it lead me to: https://github.com/LordVonAdel/os2l/blob/5ea097ad1aaf0538c5b9242040a9d564aec06b19/OS2LServer.js#L81

I've found that sometimes the `str` variable contains two JSON objects, for example:
{"evt":"btn","name":"someButton","page":"somePage","state":"on"}{"evt":"beat","change":false,"pos":17,"bpm":128,"strength":1}

And of course JSON.parse() cannot handle this so throws the error.

I'm new to the OS2L protocol but I wonder if this happens if beat and btn trigger at the same time? I'm currently having trouble reproducing it consistently. But it happens every 10 mins or so as I'm doing development here.

I'm still figuring out the best solution but wanted to post my findings here in case you were familiar with the issue.

**Comment by LordVonAdel** [comment]
could be a TCP issue. The "data" event is called for every part of a stream, and not per packet. So it could happen only half of a JSON string is there or multiple at once. That is an error in my implementation. I should check for the case when multiple stream chunks are batched together or are incomplete.

**Comment by SeanBannister** [comment]
I had a look and you're correct `net.createServer` won't wait for all data to be received if the data is arriving in chunks or if multiple JSON objects are being received in rapid succession.

I had a look at the C++ example given on the spec website http://os2l.org/OS2L.cpp and they're using a buffer which waits for the closing curly brace and then increments the buffer [Line 287]:
```
		if (*buffer == '}')
		{
			buffer++;
			return true;
		}
```

I've just written an implementation which seems to be working, I'll make a pull request. The only thing this implementation doesn't account for is curly braces inside of the JSON strings like the button name. But this seems like a safe thing to warn users about.

**Comment by SeanBannister** [comment]
I just received another "Bad OS2L package received!" error with the code I wrote 🤦 I'm really unsure why. I'll keep working on it.

**Comment by SeanBannister** [comment]
Sorry for the confusion, I just realized the error I was receiving in my last post was because I was sending bad data to OS2L not due to my JSON buffer implementation. The pull request I made earlier should still be working find.
